- name: Install the app requirements into the python venv
  hosts: app_servers
  gather_facts: no

  vars:
    hosting_user: "{{ vault_hosting_user }}"
    venv_path: /var/www/{{ hosting_user }}/data/.venv
    requirements_path: "{{ playbook_dir }}/../app/requirements.txt"

  tasks:
    - name: Install the app requirements into the venv
      ansible.builtin.pip:
        requirements: "{{ requirements_path }}"
        virtualenv: "{{ venv_path }}"
