- name: Add new domain to ispmanager
  import_playbook: playbooks/add_new_domain.yml
  tags:
    - add_new_domain

- name: Set up basic auth for the app
  import_playbook: playbooks/set_up_basic_auth.yml
  tags:
    - set_up_basic_auth

- name: Delete index.html file
  import_playbook: playbooks/delete_default_index_html_file.yml
  tags:
    - delete_index_file

- name: Create python environment
  import_playbook: playbooks/create_python_venv.yml
  tags:
    - create_python_venv

- name: Deliver app code from git
  import_playbook: playbooks/deploy_app_from_git.yml
  tags:
    - deploy_app

- name: Install the app requirements
  import_playbook: playbooks/install_app_requirements.yml
  tags:
    - install_app_requirements

- name: Create .env file for app
  import_playbook: playbooks/create_dot_env_file.yml
  tags:
    - create_dot_env_file

- name: Collect static files for the app
  import_playbook: playbooks/collect_static.yml
  tags:
    - collect_static

- name: Set up passenger wsgi
  import_playbook: playbooks/set_up_passenger_wsgi_py.yml
  tags:
    - set_up_passenger

